# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Emanuel', :city => cities.first)
#coding: utf-8
Question.create(:id => 1, :question => '明朗', :location => 'jp')
Question.create(:id => 2, :question => '好奇心が強い', :location => 'jp')
Question.create(:id => 3, :question => '積極的', :location => 'jp')
Question.create(:id => 4, :question => '引っ込み思案', :location => 'jp')
Question.create(:id => 5, :question => '素直', :location => 'jp')
Question.create(:id => 6, :question => 'あまのじゃく', :location => 'jp')
Question.create(:id => 7, :question => 'エロい', :location => 'jp')
Question.create(:id => 8, :question => '責任感が強い', :location => 'jp')
Question.create(:id => 9, :question => '頑固', :location => 'jp')
Question.create(:id => 10, :question => '協調性がある', :location => 'jp')
Question.create(:id => 11, :question => '孤高', :location => 'jp')
Question.create(:id => 12, :question => '謙虚', :location => 'jp')
Question.create(:id => 13, :question => '優しい', :location => 'jp')
Question.create(:id => 14, :question => '厳格', :location => 'jp')
Question.create(:id => 15, :question => '誠実', :location => 'jp')
Question.create(:id => 16, :question => 'チャラい', :location => 'jp')
Question.create(:id => 17, :question => '図太い', :location => 'jp')
Question.create(:id => 18, :question => '度胸がある', :location => 'jp')
Question.create(:id => 19, :question => '慎重', :location => 'jp')
Question.create(:id => 20, :question => '面倒見が良い', :location => 'jp')
Question.create(:id => 21, :question => 'わがまま', :location => 'jp')
Question.create(:id => 22, :question => '礼儀正しい', :location => 'jp')
Question.create(:id => 23, :question => '自由', :location => 'jp')
Question.create(:id => 24, :question => '個性的', :location => 'jp')
Question.create(:id => 25, :question => '繊細', :location => 'jp')
Question.create(:id => 26, :question => '大雑把', :location => 'jp')
Question.create(:id => 27, :question => '天然', :location => 'jp')
